version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: container_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - custom-network-rabbitmq

networks:
  custom-network-rabbitmq:
    driver: bridge