version: '3.7'
services:
  mongodb-primary:
    container_name: container_mongodb
    image: docker.io/bitnami/mongodb:latest
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=container_mongodb
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=admin
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=mongodb
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - mongodb_data_container:/bitnami/mongodb
    networks:
      - custom-network-mongo
  mongo-express:
    container_name: container_mongo_express
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: container_mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - mongodb-primary
    links:
      - mongodb-primary
    networks:
      - custom-network-mongo

volumes:
  mongodb_data_container:
    driver: local
networks:
  custom-network-mongo:
    driver: bridge
