version: '3.7'
services:
  redis:
    container_name: container_redis
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - custom-network-redis
  redis-commander:
    container_name: container_redis_commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=admin
    ports:
      - 8083:8081
    networks:
      - custom-network-redis

volumes:
  redis-data: {}
networks:
  custom-network-redis:
    driver: bridge
